export const VALUATION_FIELDS = [
  ['owner_name','Onr'],
  ['purchaser_name','Purch'],
  ['property_address','Addr'],
  ['survey_no','Survey'],
  ['plot_no','Plot'],
  ['door_no','Door'],
  ['village','Village'],
  ['taluka','Taluka'],
  ['district','Dist'],
  ['pin_code','PIN'],
  ['boundary_east_map','E-Map'],
  ['boundary_west_map','W-Map'],
  ['boundary_north_map','N-Map'],
  ['boundary_south_map','S-Map'],
  ['boundary_east_site','E-Site'],
  ['boundary_west_site','W-Site'],
  ['boundary_north_site','N-Site'],
  ['boundary_south_site','S-Site'],
  ['map_area','Area'],
  ['map_area_unit','Unit'],
  ['document_1','Doc1'],
  ['document_2','Doc2'],
  ['document_3','Doc3'],
  ['document_4','Doc4'],
  ['document_5','Doc5'],
  ['document_6','Doc6'],
  ['ground_floor_area','GF'],
  ['first_floor_area','FF'],
  ['terrace_floor_area','Terrace'],
];

export const FIELD_LABELS = Object.fromEntries(VALUATION_FIELDS);
