import { useEffect, useRef, useState } from 'react';

export default function FourCornerCrop({ imageUrl, onApply, onCancel }) {
  const imgRef = useRef(null);
  const [points,setPoints]=useState([{x:8,y:8},{x:92,y:8},{x:92,y:92},{x:8,y:92}]);
  const [drag,setDrag]=useState(null);
  useEffect(()=>{ const stop=()=>setDrag(null); window.addEventListener('pointerup',stop); return()=>window.removeEventListener('pointerup',stop);},[]);
  function move(i,e){ const r=imgRef.current?.getBoundingClientRect(); if(!r)return; const x=Math.max(1,Math.min(99,(e.clientX-r.left)/r.width*100)); const y=Math.max(1,Math.min(99,(e.clientY-r.top)/r.height*100)); setPoints(p=>p.map((v,j)=>j===i?{x,y}:v)); }
  return <div className="fixed inset-0 z-[70] overflow-y-auto bg-slate-950"><div className="mx-auto min-h-screen max-w-3xl bg-slate-100"><header className="sticky top-0 z-20 flex justify-between bg-slate-900 px-4 py-3 text-white"><div><div className="text-xs text-slate-300">Document crop</div><h2 className="font-semibold">Set Four Corners</h2></div><button onClick={onCancel} className="rounded-lg bg-white/10 px-3 py-2">Cancel</button></header><div className="p-4"><div className="relative overflow-hidden rounded-2xl bg-black"><img ref={imgRef} src={imageUrl} className="block max-h-[75vh] w-full object-contain" draggable="false"/><svg className="pointer-events-none absolute inset-0 h-full w-full" preserveAspectRatio="none" viewBox="0 0 100 100"><polygon points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="rgba(37,99,235,.12)" stroke="white" strokeWidth=".5"/></svg>{points.map((p,i)=><button key={i} onPointerDown={e=>{e.preventDefault();setDrag(i)}} onPointerMove={e=>{if(drag===i)move(i,e)}} className="absolute h-9 w-9 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-blue-600 text-xs font-bold text-white" style={{left:`${p.x}%`,top:`${p.y}%`}}>{i+1}</button>)}</div><div className="mt-3 rounded-xl bg-blue-50 p-3 text-xs text-blue-800">Drag each blue point to the four corners of the document.</div><button onClick={()=>{const img=imgRef.current;onApply(points.map(p=>({x:p.x/100*img.naturalWidth,y:p.y/100*img.naturalHeight})));}} className="mt-3 w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">Apply Crop</button></div></div></div>;
}
