import { useEffect, useMemo, useRef, useState } from 'react';
import Tesseract from 'tesseract.js';
import FourCornerCrop from './FourCornerCrop';
import { canvasToBlob, createEnhancedCanvas } from '../utils/imageProcessing';

export default function ScanEditor({ page, onDone, onCancel }) {
  const imgRef=useRef(null);
  const [mode,setMode]=useState(null), [selection,setSelection]=useState(null), [dragging,setDragging]=useState(null);
  const [ocrText,setOcrText]=useState(page.editedText||page.ocrText||''), [status,setStatus]=useState('');
  const [progress,setProgress]=useState(0), [rotation,setRotation]=useState(page.rotation||0), [zoom,setZoom]=useState(1);
  const [busy,setBusy]=useState(false), [showCorners,setShowCorners]=useState(false), [sourceUrl,setSourceUrl]=useState(page.imageUrl);
  const [ocrMode,setOcrMode]=useState('eng+guj'), [preprocess,setPreprocess]=useState('enhanced');
  const imageStyle=useMemo(()=>({transform:`rotate(${rotation}deg) scale(${zoom})`,transformOrigin:'center center'}),[rotation,zoom]);
  useEffect(()=>()=>{ if(sourceUrl&&sourceUrl!==page.imageUrl) URL.revokeObjectURL(sourceUrl); },[sourceUrl,page.imageUrl]);
  function reset(){setRotation(0);setZoom(1)}
  function choose(m){setMode(m);setSelection(null);setStatus('');reset()}
  function pointerDown(e){if(mode!=='rectangle')return;const r=imgRef.current?.getBoundingClientRect();if(!r)return;const x=Math.max(0,Math.min(e.clientX-r.left,r.width)),y=Math.max(0,Math.min(e.clientY-r.top,r.height));setSelection({x,y,w:1,h:1});setDragging({x,y});e.currentTarget.setPointerCapture?.(e.pointerId)}
  function pointerMove(e){if(!dragging)return;const r=imgRef.current?.getBoundingClientRect();if(!r)return;const x=Math.max(0,Math.min(e.clientX-r.left,r.width)),y=Math.max(0,Math.min(e.clientY-r.top,r.height));setSelection({x:Math.min(dragging.x,x),y:Math.min(dragging.y,y),w:Math.abs(x-dragging.x),h:Math.abs(y-dragging.y)})}
  function stop(){setDragging(null)}
  async function makeCanvas(){
    const img=imgRef.current;if(!img)throw Error('Image not ready');
    const sw=img.naturalWidth,sh=img.naturalHeight;let sx=0,sy=0,cw=sw,ch=sh;
    if(mode==='rectangle'&&selection){const r=img.getBoundingClientRect(),fx=sw/r.width,fy=sh/r.height;sx=selection.x*fx;sy=selection.y*fy;cw=selection.w*fx;ch=selection.h*fy;if(cw<20||ch<20)throw Error('Please select a larger area.')}
    const c=document.createElement('canvas');c.width=Math.round(cw);c.height=Math.round(ch);const ctx=c.getContext('2d');ctx.drawImage(img,sx,sy,cw,ch,0,0,c.width,c.height);
    if(rotation%360){const a=((rotation%360)+360)%360*Math.PI/180,r=document.createElement('canvas'),q=rotation%180!==0;r.width=q?c.height:c.width;r.height=q?c.width:c.height;const rc=r.getContext('2d');rc.translate(r.width/2,r.height/2);rc.rotate(a);rc.drawImage(c,-c.width/2,-c.height/2);return r}return c;
  }
  async function runOCR(){setBusy(true);setProgress(0);setStatus('Preparing image...');try{let c=await makeCanvas();if(preprocess!=='original')c=createEnhancedCanvas(c,{contrast:preprocess==='strong'?1.55:1.3,brightness:preprocess==='strong'?1.08:1.03,scale:preprocess==='strong'?2.5:2});const b=await canvasToBlob(c);const u=URL.createObjectURL(b);setSourceUrl(u);setStatus(`OCR running: ${ocrMode}`);const result=await Tesseract.recognize(c,ocrMode,{logger:m=>{if(typeof m.progress==='number')setProgress(Math.round(m.progress*100));if(m.status)setStatus(m.status)}});setOcrText(result.data.text||'');setStatus('OCR completed. Please correct the text.')}catch(e){console.error(e);setStatus(e.message||'OCR failed.')}finally{setBusy(false)}}
  async function applyCorners(points){setBusy(true);setStatus('Preparing document crop...');try{const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=page.imageUrl});const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.max(0,Math.floor(Math.min(...xs))),minY=Math.max(0,Math.floor(Math.min(...ys))),maxX=Math.min(img.naturalWidth,Math.ceil(Math.max(...xs))),maxY=Math.min(img.naturalHeight,Math.ceil(Math.max(...ys)));const c=document.createElement('canvas');c.width=Math.max(1,maxX-minX);c.height=Math.max(1,maxY-minY);c.getContext('2d').drawImage(img,minX,minY,c.width,c.height,0,0,c.width,c.height);const b=await canvasToBlob(c);const u=URL.createObjectURL(b);setSourceUrl(u);setMode('document');setShowCorners(false);setStatus('Document area selected. For best accuracy use Enhanced and run OCR.')}catch(e){setStatus('Could not crop document.')}finally{setBusy(false)}}
  function save(){onDone({...page,scanMode:mode,crop:selection,rotation,ocrText,editedText:ocrText})}
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950"><div className="mx-auto min-h-screen max-w-3xl bg-slate-100"><header className="sticky top-0 z-30 flex justify-between bg-slate-900 px-4 py-3 text-white"><div><div className="text-xs text-slate-300">Page {page.pageNumber}</div><h2 className="font-semibold">Scan & Improve OCR</h2></div><button onClick={onCancel} className="rounded-lg bg-white/10 px-3 py-2">Close</button></header><div className="p-4">
    {!mode?<div className="rounded-2xl bg-white p-5 shadow"><h3 className="text-lg font-semibold">Choose Scan Mode</h3><p className="mt-1 text-sm text-slate-500">For camera photos, crop the document first whenever possible.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><button onClick={()=>choose('full')} className="rounded-xl bg-slate-900 p-5 text-left text-white">📄<div className="mt-2 font-semibold">Full Image</div><div className="text-xs text-slate-300">OCR whole page</div></button><button onClick={()=>choose('rectangle')} className="rounded-xl border p-5 text-left">▣<div className="mt-2 font-semibold">Rectangle</div><div className="text-xs text-slate-500">OCR selected text</div></button><button onClick={()=>{setMode('document');setShowCorners(true)}} className="rounded-xl border border-blue-300 bg-blue-50 p-5 text-left">📐<div className="mt-2 font-semibold text-blue-900">Document Crop</div><div className="text-xs text-blue-700">Set 4 corners</div></button></div></div>:<><div className="overflow-hidden rounded-2xl bg-black"><div className="relative flex min-h-[45vh] items-center justify-center overflow-auto select-none" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={stop} onPointerCancel={stop}><img ref={imgRef} src={sourceUrl} className="block max-h-[65vh] max-w-full object-contain" style={imageStyle} draggable="false"/>{mode==='rectangle'&&selection&&<div className="pointer-events-none absolute border-2 border-white bg-blue-500/10" style={{left:selection.x,top:selection.y,width:selection.w,height:selection.h}}/>}</div></div>
    <div className="mt-3 rounded-2xl bg-white p-3 shadow"><div className="flex flex-wrap gap-2"><button onClick={()=>setRotation(v=>(v+90)%360)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">↻ Rotate</button><button onClick={()=>setZoom(v=>Math.min(2.5,v+.25))} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">＋ Zoom</button><button onClick={()=>setZoom(v=>Math.max(.75,v-.25))} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">－ Zoom</button><button onClick={reset} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">Reset</button><button onClick={()=>{setMode(null);setSourceUrl(page.imageUrl);reset()}} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">Change Scan</button>{mode==='document'&&<button onClick={()=>setShowCorners(true)} className="rounded-lg bg-blue-100 px-3 py-2 text-sm font-medium text-blue-800">📐 Adjust Corners</button>}</div><div className="mt-2 text-xs text-slate-500">Rotation {rotation}° · Zoom {Math.round(zoom*100)}%</div></div>
    <div className="mt-3 rounded-2xl bg-white p-4 shadow"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium text-slate-500">OCR language<select value={ocrMode} onChange={e=>setOcrMode(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="eng+guj">Gujarati + English</option><option value="guj">Gujarati only</option><option value="eng">English only</option></select></label><label className="text-xs font-medium text-slate-500">Enhancement<select value={preprocess} onChange={e=>setPreprocess(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="original">Original</option><option value="enhanced">Enhanced</option><option value="strong">Strong</option></select></label></div><button onClick={runOCR} disabled={busy||(mode==='rectangle'&&!selection)} className="mt-4 w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white disabled:opacity-40">{busy?'🔎 Processing...':'🔎 Extract Text'}</button><button onClick={()=>{setPreprocess('strong');setTimeout(runOCR,50)}} disabled={busy} className="mt-2 w-full rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800">🔄 Try Better OCR</button></div>
    {status&&<div className="mt-3 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{status}</div>}{progress>0&&progress<100&&<div className="mt-3 rounded-xl bg-white p-3"><div className="text-xs text-slate-500">OCR progress {progress}%</div><div className="mt-1 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-blue-600" style={{width:`${progress}%`}}/></div></div>}
    <section className="mt-4 rounded-2xl bg-white p-4 shadow"><div className="mb-2 flex justify-between"><h3 className="font-semibold">OCR Text</h3><span className="text-xs text-slate-400">Fully editable</span></div><textarea value={ocrText} onChange={e=>setOcrText(e.target.value)} rows={14} className="w-full rounded-xl border p-3 text-sm leading-6 outline-none focus:border-blue-500" placeholder="OCR text will appear here..."/><button onClick={save} className="mt-3 w-full rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white">✓ Save Page Text</button></section></>}
    </div></div>{showCorners&&<FourCornerCrop imageUrl={page.imageUrl} onApply={applyCorners} onCancel={()=>setShowCorners(false)}/>}</div>;
}
